spring.application.name=arogya-ai-backend

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/arogya_ai?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=Palak@@23

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.fail-on-empty-beans=false

app.jwt.secret=arogya-ai-super-secret-key-change-this-in-production-2026
app.jwt.expiration=86400000